services:
  # --- FRONTEND ---
  client:
    build:
      dockerfile: ./Dockerfile.client
      args:
        # ⚠️ ВАЖНО: При деплое на реальный сервер заменить localhost
        # на IP  сервера
        - VITE_SERVER_URL=http://localhost:3000
        - VITE_PB_URL=http://localhost:8090
    ports:
      - '80:80'
    depends_on:
      - server

  # --- BACKEND ---
  server:
    build:
      dockerfile: ./Dockerfile.server
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
