name: Build and Deploy server

on:
  push:
    branches:
    - 'firebase'
    paths:
      - 'apps/server/**/*'
      - 'packages/**/*'
      - 'Dockerfile.server'

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: code checkout
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: build and push the docker image
      env:
        GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        IMAGE_TAG: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/alias/game-server:latest
      run: |
        gcloud auth configure-docker $GOOGLE_REGION-docker.pkg.dev
        docker build \
          --build-arg FIREBASE_projectId='${{ secrets.VITE_FIREBASE_PROJECTID }}' \
          --build-arg SERVER_URL='${{ secrets.SERVER_URL }}' \
          -f ./Dockerfile.server -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    - name: deploy to Cloud Run
      env:
        GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        IMAGE_TAG: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/alias/game-server:latest
      run: |
        # Create a temporary env file to handle special characters in secrets
        cat <<EOF > .env.production
        FIREBASE_SERVICE_ACCOUNT_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
        OAUTH_DISCORD_CLIENT_SECRET=${{ secrets.OAUTH_DISCORD_CLIENT_SECRET }}
        OAUTH_DISCORD_CLIENT_ID=${{ secrets.OAUTH_DISCORD_CLIENT_ID }}
        FIREBASE_apiKey=${{ secrets.VITE_FIREBASE_APIKEY }}
        FIREBASE_authDomain=${{ secrets.VITE_FIREBASE_AUTHDOMAIN }}
        FIREBASE_storageBucket=${{ secrets.VITE_FIREBASE_STORAGEBUCKET }}
        FIREBASE_messagingSenderId=${{ secrets.VITE_FIREBASE_MESSAGINGSENDERID }}
        FIREBASE_appId=${{ secrets.VITE_FIREBASE_APPID }}
        FIREBASE_measurementId=${{ secrets.VITE_FIREBASE_MEASUREMENTID }}
        OAUTH_DISCORD_URL=${{ secrets.OAUTH_DISCORD_URL }}
        OAUTH_DISCORD_SCOPE=${{ secrets.OAUTH_DISCORD_SCOPE }}
        OAUTH_DISCORD_REDIRECT_URI=${{ secrets.OAUTH_DISCORD_REDIRECT_URI }}
        OAUTH_DISCORD_PUBLIC_KEY=${{ secrets.OAUTH_DISCORD_PUBLIC_KEY }}
        OAUTH_DISCORD_APPLLICATION_ID=${{ secrets.OAUTH_DISCORD_APPLLICATION_ID }}
        EOF

        gcloud run deploy game-server \
          --image=$IMAGE_TAG \
          --region=$GOOGLE_REGION \
          --port=3000 \
          --cpu=1 \
          --memory=256Mi \
          --min-instances=1 \
          --max-instances=1 \
          --concurrency=80 \
          --timeout=300 \
          --ingress=all \
          --allow-unauthenticated \
          --quiet
