name: Build and Deploy client

on:
  push:
    branches:
    - 'firebase'
path:
  - apps/client
  - packages
  - Dockerfile.client

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

    - name: code checkout
      uses: actions/checkout@v4

    - uses: 'google-github-actions/auth@v3'
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: build and push the docker image
      env:
        GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        IMAGE_TAG: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/alias/game-client:latest
      run: |
        gcloud auth configure-docker $GOOGLE_REGION-docker.pkg.dev
        docker build -f ./Dockerfile.client -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    - name: deploy to Cloud Run
      env:
        GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
        IMAGE_TAG: ${{ secrets.GOOGLE_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/alias/game-client:latest
      run: gcloud run deploy game-client --region $GOOGLE_REGION --image $IMAGE_TAG
